default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: furima_38982_development


test:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: furima_38982_test

production:
  <<: *default
  adapter: mysql2
  database: furima-38982_production
  username: root
  password: <%= ENV['DATABASE_PASSWORD'] %>
  socket: /var/lib/mysql/mysql.sock